import SideBar from "@/components/shared/SideBar";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SideBar />
        <div className="min-h-screen">{children}</div>
      </body>
    </html>
  );
}
